# Generated by Django 5.2.4 on 2025-08-08 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'standard'], name='core_studen_school__17e9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['standard'], name='core_studen_standar_ee2611_idx'),
        ),
        migrations.AddIndex(
            model_name='taskevaluation',
            index=models.Index(fields=['student', 'assignment'], name='core_taskev_student_0ecbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskevaluation',
            index=models.Index(fields=['status'], name='core_taskev_status_84c142_idx'),
        ),
        migrations.AddIndex(
            model_name='taskevaluation',
            index=models.Index(fields=['assignment', 'status'], name='core_taskev_assignm_72d13a_idx'),
        ),
    ]
