# Generated by Django 5.2.4 on 2025-08-08 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_core_studen_school__17e9c3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['standard'], name='core_assign_standar_2f0fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['subject', 'standard'], name='core_assign_subject_6599a8_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_date', 'end_date'], name='core_assign_start_d_50c3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_at'], name='core_assign_created_4a13a8_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['taluka'], name='core_school_taluka__643341_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['udise_code'], name='core_school_udise_c_711b1d_idx'),
        ),
    ]
